### ISSUE TITLE
Is there a way to create a new collection?

### ISSUE THREAD

**Issue by dpgeekzero** [xyproto/wallutils#5]
Perhaps I'm missing it, but I don't see how to create my own collections.

**Comment by xyproto** [comment]
Thanks for reporting. I should document this.

One way is to create a directory with filenames on the form `name_1900x1200.jpg`, where the name usually is the same as the collection and the resolutions may vary.

**Comment by xyproto** [comment]
I added a short section about wallpaper collections in `README.md`.

**Comment by paratheta** [comment]
@xyproto I'm not sure if this is intentional but is the wallpaper collection creation limited to `/usr/share/wallpapers` and `/usr/share/backgrounds`? Moreover, do I need to rename all of my wallpaper files and add their resolution in the filename?

Ideally, I should be able to just point out a user owned directory to `setcollection` and it should search for wallpapers inside that directory recursively and then `setcollection mywalls` inside `.config/sway/config` should pick a random wallpaper from that collection.

**Comment by xyproto** [comment]
Yes, currently it's limited to `/usr/share/wallpapers` and `/usr/share/backgrounds`. I agree that I should make this more configurable (pull requests are welcome if I'm not fast enough at fixing this :) ).

For setting a random wallpaper from a directory of images, the `setrandom` utility can be used.
